# Generated by Django 4.2.6 on 2023-10-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_music_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='lyrics',
            field=models.FileField(blank=True, null=True, upload_to='lyrics/'),
        ),
    ]
