# Generated by Django 4.2.6 on 2023-10-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
