# Generated by Django 4.2.6 on 2023-10-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_music_lyrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('meaning', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
