# Generated by Django 4.2.6 on 2023-10-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_music_album_delete_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocab',
            name='type',
        ),
    ]
