# Generated by Django 4.2.6 on 2023-10-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_vocab_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='vocabs',
            field=models.ManyToManyField(related_name='music', to='music.vocab'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='eng',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='meaning',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
