# Generated by Django 4.2.6 on 2023-10-15 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_music_voabulary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='vocabs',
        ),
        migrations.DeleteModel(
            name='Vocab',
        ),
    ]
