# Generated by Django 4.2.6 on 2023-10-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_vocab_music_vocabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='vocabs',
        ),
        migrations.AddField(
            model_name='music',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Vocab',
        ),
    ]
